export const cards = [
  {
    id: 1,
    title: "AI Artists",
    desc: "Aser Aspire 5 16 512Gb AMD ryzen 8 4GB RAM",
    price: "N200,000",
    price2: "(542)",
    img: "/img/pix2.png",
  },
  {
    id: 2,
    title: "AI Artists",
    desc: "Aser Aspire 5 16 512Gb AMD ryzen 8 4GB RAM",
    price: "N200,000",
    price2: "(542)",
    img: "/img/pix2.png",
  },
  {
    id: 3,
    title: "AI Artists",
    desc: "Aser Aspire 5 16 512Gb AMD ryzen 8 4GB RAM",
    price: "N200,000",
    price2: "(542)",
    img: "/img/pix2.png",
  },
  {
    id: 4,
    title: "AI Artists",
    desc: "Aser Aspire 5 16 512Gb AMD ryzen 8 4GB RAM",
    price: "N200,000",
    price2: "(542)",
    img: "/img/pix2.png",
  },
  {
    id: 5,
    title: "AI Artists",
    desc: "Aser Aspire 5 16 512Gb AMD ryzen 8 4GB RAM",
    price: "N200,000",
    price2: "(542)",
    img: "/img/pix2.png",
  },
  {
    id: 6,
    title: "AI Artists",
    desc: "Aser Aspire 5 16 512Gb AMD ryzen 8 4GB RAM",
    price: "N200,000",
    price2: "(542)",
    img: "/img/pix2.png",
  },
  {
    id: 7,
    title: "AI Artists",
    desc: "Aser Aspire 5 16 512Gb AMD ryzen 8 4GB RAM",
    price: "N200,000",
    price2: "(542)",
    img: "/img/pix2.png",
  },
];

export const gigs = [
  {
    id: 1,
    img: "./img/bg.png",
    pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ai art character from your images and prompts",
    price: 59,
    star: 5,
    username: "Anna Bell",
  },
  {
    id: 2,
    img: "./img/bg.png",
    pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will create ultra high quality character art with ai",
    price: 79,
    star: 5,
    username: "Lannie Coleman",
  },
  {
    id: 3,
    img: "./img/bg.png",
    pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
    desc: "I will creating unique ai generated artworks mid journey ai artist",
    price: 112,
    star: 5,
    username: "Carol Steve",
  },
];
export const products = [
  {
    id: 0,
    name: "COLORX WIPES",
    price: "N33,040.00",
    img: "/img/p1.png",
    availability: "in stock (234)",
    category: "Accessories",
    color: ["BLACK", "GOLD", "APPOLO"],
    description: "This is a very cool feature",
  },
  {
    id: 1,
    name: "PS5",
    price: "N733,040.00",
    img: "/img/ps6.jpg",
    availability: "in stock (10)",
    category: "gaming",
    color: ["BLACK", "WHITE", "PURPLE"],
    description: "This is very good console",
  },
  {
    id: 2,
    name: "SHOES",
    price: "N53,040.00",
    img: "/img/lifestyle.png",
    availability: "in stock (500)",
    category: "Wears",
    color: ["YELLOW", "BLUE", "GREEN"],
    description: "I LOVE THESE WAERS SO MUCH",
  },
];
